### ISSUE TITLE
Migrate to python 3

### ISSUE THREAD

**Issue by bhipple** [nix-community/nixops-gce#2]
[NixOS/nixops](https://github.com/NixOS/nixops) has moved to python3 on the `master` branch, which means it no longer builds with the `nixops-gce` plugin (see https://github.com/NixOS/nixops/issues/1258). A workaround is to checkout an older NixOps, but we should start the migration here as well so that the master branches work with each other.

I don't use GCE and don't plan to send any PRs, but I figured I'd open an issue to help track status for others. For inspiration, here are the changes that we made to `nixops-aws`:
https://github.com/NixOS/nixops-aws/issues/29

Many of these can be done in-place and reviewed/tested/merged using the cmds listed there, which reduces the size of the final backwards-incompatible diff and allows for incremental forward progress.

**Comment by tewfik-ghariani** [comment]
Now that https://github.com/nix-community/nixops-gce/pull/4 is merged,this can be closed ^^

Thanks!
